import {templates,statusLabel,initialValues} from './templates.js';
import {configured,createApi,randomToken,inviteUrl} from './api.js';
import {downloadPdf} from './pdf.js';
const root=document.querySelector('#app');
const state={role:null,students:[],documents:[],student:null,current:null,section:null,tab:'fields',filter:'',dirty:new Set(),timers:new Map(),pending:new Map(),errors:new Map(),catalogue:null};
const config=window.ESCOLA_CONFIG||{};
let api=null,token=new URLSearchParams(location.hash.slice(1)).get('convite');
try{if(configured(config))api=createApi(config);}catch(e){notify(e.message,true);}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(v.length===10?v+'T12:00:00':v)):'Sem prazo';
const stamp=v=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v));
function notify(message,error=false){const el=document.querySelector('#notice');el.textContent=message;el.className=error?'show error':'show';clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.className='',error?15000:5000);}
function failure(e){let message=e.message||'Não foi possível concluir. Tente novamente.';if(message.includes('duplicate key'))message='Já existe um documento desse tipo, ano, bimestre e componente para este estudante.';if(message.includes('Failed to fetch'))message='Sem conexão com o servidor. O texto continua nesta aba; tente salvar novamente antes de sair.';notify(message,true);}
function shell(body){root.innerHTML=`<aside class="sidebar"><a class="brand" href="#" data-action="home"><span class="brand-mark">LP<span>•</span></span><span>Luigi Pirandello<small>Educação Especial</small></span></a><div class="nav-label">ESPAÇO DE TRABALHO</div><nav><button data-action="home" class="nav-item active">▤ <span>${state.role==='contributor'?'Meu preenchimento':'Estudantes e documentos'}</span></button><button data-action="guide" class="nav-item">ⓘ <span>Guia dos formulários</span></button></nav><div class="sidebar-bottom"><span class="status-dot"></span> ${state.role==='admin'?'Administrador':state.role==='contributor'?'Acesso por convite':'Acesso restrito'}<p>Unidade Regional de Ensino Leste 1</p>${state.role==='admin'?'<button class="text-button" data-action="logout">Sair com segurança →</button>':''}</div></aside><div class="workspace"><header class="topbar"><span>GESTÃO PEDAGÓGICA <span class="slash">/</span> DOCUMENTAÇÃO</span><span class="school-tag">E.E. Luigi Pirandello</span></header><main id="conteudo" tabindex="-1">${body}</main><footer>Estudo de Caso · PAEE · PEI · Família <span>Os registros oficiais e as assinaturas seguem os procedimentos da escola.</span></footer></div>`;}
function login(){state.role=null;shell(`<div class="intro"><p class="eyebrow">PLANEJAR. ACOMPANHAR. REGISTRAR.</p><h1>Um espaço para construir<br>a educação inclusiva.</h1><p class="lede">Cada profissional contribui com sua área.<br>A escola acompanha, revisa e reúne tudo em um documento.</p></div><div class="login-grid"><section class="card login-card"><div class="card-kicker">ACESSO DA GESTÃO</div><h2>Entrar como administrador</h2><form id="login-form"><label>E-mail<input name="email" type="email" autocomplete="username" required placeholder="seu.email@educacao.sp.gov.br" ${!api?'disabled':''}></label><label>Senha<input name="password" type="password" autocomplete="current-password" required ${!api?'disabled':''}></label><button class="primary full" ${!api?'disabled':''}>Entrar no painel <span>→</span></button></form><button type="button" class="text-button recovery-link" data-action="forgot-password" ${!api?'disabled':''}>Esqueci minha senha</button>${!api?'<p class="callout">A ativação do banco e do acesso está pendente. Nenhum dado é gravado nesta tela.</p>':'<p class="muted small">Use a conta cadastrada pela gestão. A sessão fica apenas nesta aba. Para redefinir a senha, solicite a recuperação da conta ao responsável pela implantação.</p>'}</section><section class="login-aside"><span class="eyebrow">TRABALHO EM EQUIPE</span><h2>O formulário certo,<br>para cada responsabilidade.</h2><ol class="journey"><li><span>01</span><div><strong>A gestão organiza</strong><p>Estudantes, documentos, áreas e prazos.</p></div></li><li><span>02</span><div><strong>A equipe contribui</strong><p>Um convite abre somente as áreas atribuídas.</p></div></li><li><span>03</span><div><strong>A escola revisa e finaliza</strong><p>Histórico preservado e PDF com cabeçalho.</p></div></li></ol><button class="text-button" data-action="guide">Conhecer os cinco formulários →</button></section></div>`);}
function passwordRecovery(){
 state.role=null;
 shell(`<div class="intro"><p class="eyebrow">RECUPERAÇÃO DE ACESSO</p><h1>Crie uma nova senha.</h1><p class="lede">Use pelo menos 8 caracteres.<br>Depois você entrará diretamente no painel.</p></div><div class="login-grid"><section class="card login-card"><div class="card-kicker">NOVA SENHA</div><h2>Redefinir acesso</h2><form id="new-password-form"><label>Nova senha<input name="password" type="password" autocomplete="new-password" minlength="8" required></label><label>Confirmar nova senha<input name="confirm" type="password" autocomplete="new-password" minlength="8" required></label><button class="primary full">Salvar nova senha <span>→</span></button></form></section></div>`);
}
function guide(){shell(`<div class="page-heading"><div><p class="eyebrow">DOCUMENTO ORIENTADOR</p><h1>Cinco modelos. Um fluxo de trabalho.</h1><p class="muted">Referência: documento fornecido, com 99 páginas. As respostas dos exemplos não são utilizadas.</p></div><button data-action="home">Voltar</button></div><div class="guide-grid">${Object.entries(templates).map(([id,t],i)=>`<button class="card guide-card" data-action="catalogue" data-id="${id}"><span class="card-kicker">MODELO 0${i+1} · PÁG. ${t.pages}</span><h2>${t.name}</h2><p>${t.owner}</p><span class="text-link">Ver áreas e perguntas →</span></button>`).join('')}</div><div class="card guide-notes"><h2>Como usar as orientações</h2><p>Estudo de Caso e PAEE são organizados por ano. O PEI é criado para cada componente e bimestre. O acolhimento registra a conversa inicial; o retorno registra o acompanhamento bimestral.</p><p>O orientador cita 30 dias letivos para Estudo de Caso e PAEE. Defina a data considerando o calendário escolar. Os prazos são ajustáveis, pois a tabela das páginas 52–53 usa “trimestral” e as orientações operacionais e os modelos usam “bimestral”.</p><p>O preenchimento da plataforma apoia o trabalho da escola. O lançamento na SED e a coleta de assinaturas continuam pelos canais indicados no orientador.</p><p>O PDF preserva o cabeçalho fornecido, os campos e os quadros. Textos extensos geram continuação, portanto a quantidade de páginas e a distribuição não serão idênticas às do formulário vazio.</p></div>`);}
function catalogue(id){const t=templates[id];if(!t)throw Error('Modelo inexistente.');state.catalogue=id;shell(`<div class="page-heading"><div><p class="eyebrow">MODELO · PÁGINAS ${t.pages}</p><h1>${t.name}</h1><p>${t.owner}</p></div><button data-action="guide">Todos os modelos</button></div><p class="callout">Consulta das perguntas. Para preencher e guardar respostas, entre no painel ou abra um convite.</p><div class="catalogue">${t.sections.map(s=>`<details class="card"><summary>${esc(s.title)} <span>${s.fields.length} campo(s)</span></summary>${s.hint?`<p class="hint">${esc(s.hint)}</p>`:''}<ul>${s.fields.map(f=>`<li>${esc(f.label)}${f.options.length?`<p class="muted small">${f.options.map(esc).join(' · ')}</p>`:''}</li>`).join('')}</ul></details>`).join('')}</div>`);}
async function loadDashboard(){const d=await api.admin('list');state.students=d.students;state.documents=d.documents;}
function dashboard(){
 const docs=state.documents, visible=state.students.filter(s=>(s.name+' '+s.grade).toLocaleLowerCase('pt-BR').includes(state.filter.toLocaleLowerCase('pt-BR')));
 shell(`<div class="page-heading"><div><p class="eyebrow">PAINEL DA ESCOLA</p><h1>Estudantes e documentos</h1><p class="muted">Organize as contribuições. Acompanhe o que falta. Finalize com confiança.</p></div><button class="primary" data-action="new-student">＋ Cadastrar estudante</button></div><div class="metrics"><div><span>Estudantes</span><strong>${state.students.length}</strong></div><div><span>Em elaboração</span><strong>${docs.filter(d=>d.status!=='final').length}</strong></div><div><span>Com áreas para revisar</span><strong>${docs.filter(d=>Number(d.submitted)>0).length}</strong></div><div><span>Documentos finalizados</span><strong>${docs.filter(d=>d.status==='final').length}</strong></div></div><section class="card student-panel"><div class="panel-title"><h2>Acompanhamento individual</h2><label class="search"><span class="sr-only">Buscar estudante ou turma</span><input id="search" value="${esc(state.filter)}" placeholder="Buscar estudante ou turma…" type="search"></label></div><div id="student-results">${studentRows(visible)}</div></section>`);
}
function studentRows(list){return list.length?`<div class="table-wrap"><table><thead><tr><th>Estudante</th><th>Turma</th><th>Documentos</th><th>Para revisar</th><th></th></tr></thead><tbody>${list.map(s=>{const ds=state.documents.filter(d=>d.student_id===s.id);return `<tr><td><strong>${esc(s.name)}</strong></td><td>${esc(s.grade)}</td><td>${ds.length}</td><td>${ds.some(d=>Number(d.submitted)>0)?'<span class="badge submitted">Revisão pendente</span>':'<span class="muted">—</span>'}</td><td><button class="text-button" data-action="student" data-id="${s.id}">Abrir →</button></td></tr>`;}).join('')}</tbody></table></div>`:`<div class="empty"><span class="empty-symbol">▤</span><h3>${state.students.length?'Nenhum resultado':'Comece pelo primeiro estudante'}</h3><p>${state.students.length?'Experimente outro nome ou turma.':'Depois do cadastro, escolha o documento e distribua as áreas para a equipe.'}</p>${!state.students.length?'<button data-action="new-student">Cadastrar estudante</button>':''}</div>`;}
function studentPage(){const s=state.student;const docs=state.documents.filter(d=>d.student_id===s.id);shell(`<button class="text-button back" data-action="home">← Todos os estudantes</button><div class="page-heading"><div><p class="eyebrow">ACOMPANHAMENTO INDIVIDUAL</p><h1>${esc(s.name)}</h1><p class="muted">${esc(s.grade)}${s.birth_date?' · Nascimento: '+date(s.birth_date):''}</p></div><div class="actions"><button data-action="edit-student">Editar cadastro</button><button class="primary" data-action="new-document">＋ Novo documento</button></div></div><div class="document-grid">${docs.map(d=>`<article class="card document-card"><span class="badge ${d.status}">${statusLabel[d.status]}</span><h2>${templates[d.kind].name}</h2><p>${d.year}${d.term?' · '+d.term+'º bimestre':''}${d.subject?' · '+esc(d.subject):''}</p><div class="progress-label"><span>Áreas aprovadas</span><strong>${d.approved} de ${d.total}</strong></div><progress max="${d.total}" value="${d.approved}" aria-label="Áreas aprovadas"></progress><div class="doc-bottom"><small>Prazo: ${date(d.due_date)}</small><button class="text-button" data-action="document" data-id="${d.id}">Abrir →</button></div></article>`).join('')||'<div class="card empty"><h2>Nenhum documento criado</h2><p>Comece pelo Estudo de Caso ou selecione o formulário de que precisa.</p><button class="primary" data-action="new-document">Criar documento</button></div>'}</div>`);}
const currentSec=()=>state.current.sections.find(s=>s.key===state.section);
function editor(){
 const c=state.current,t=templates[c.document.kind],sec=currentSec();
 if(!sec){state.section=c.sections[0]?.key;if(!state.section)throw Error('Este convite não contém áreas.');}
 const allowed=t.sections.filter(s=>c.sections.some(v=>v.key===s.id));
 shell(`<button class="text-button back" data-action="${state.role==='admin'?'student-back':'invite-refresh'}">${state.role==='admin'?'← Documentos do estudante':'↻ Atualizar convite'}</button><div class="page-heading compact"><div><p class="eyebrow">${esc(c.student.name)} · ${esc(c.student.grade)}</p><h1>${t.name}</h1><p class="muted">${c.document.year}${c.document.term?' · '+c.document.term+'º bimestre':''}${c.document.subject?' · '+esc(c.document.subject):''} <span class="dot-sep">·</span> Prazo: ${date(c.document.due_date)}</p></div><div class="actions">${state.role==='admin'?`${c.document.status!=='final'?'<button data-action="deadline">Ajustar prazo</button>':''}<button data-action="pdf">↓ ${c.document.status==='final'?'Baixar PDF':'PDF de rascunho'}</button>${c.document.status==='final'?'<button data-action="reopen-document">Abrir nova edição</button>':'<button class="primary" data-action="finalize">Finalizar documento</button>'}`:'<button class="primary" data-action="submit-invite">Enviar para revisão →</button>'}</div></div>${state.role==='contributor'?`<div class="invitation-note">Convite para <strong>${esc(c.invitation.label)}</strong> · válido até ${stamp(c.invitation.expires_at)}. Você pode acessar somente as áreas abaixo.</div>`:''}${c.document.status==='final'?'<div class="callout success">Documento finalizado. As respostas desta edição estão protegidas contra alterações.</div>':''}<div class="tabs"><button data-action="tab" data-id="fields" class="${state.tab==='fields'?'selected':''}">Áreas do documento</button>${state.role==='admin'?`<button data-action="tab" data-id="invites" class="${state.tab==='invites'?'selected':''}">Convites</button><button data-action="tab" data-id="editions" class="${state.tab==='editions'?'selected':''}">Edições finalizadas</button>`:''}</div>${state.tab==='fields'?`<div class="editor-layout"><nav class="section-nav" aria-label="Áreas do documento">${allowed.map((s,i)=>{const v=c.sections.find(v=>v.key===s.id);return `<button data-action="section" data-id="${s.id}" class="${state.section===s.id?'selected':''}"><span class="section-number">${String(i+1).padStart(2,'0')}</span><span>${esc(s.title.replace(/^[IVX]+\s*[-.]\s*/,''))}<small>${statusLabel[v.status]}</small></span>${v.status==='approved'?'<span class="check">✓</span>':''}</button>`;}).join('')}</nav><section class="card editor-card">${sectionBody()}</section></div>`:state.tab==='invites'?invitesBody():editionsBody()}`);
}
function fieldInput(f,value,disabled){const attrs=`data-field="${f.id}" id="field-${f.id}" ${disabled?'disabled':''}`;const label=`<label for="field-${f.id}">${esc(f.label)}</label>`;
 if(f.type==='multiselect')return `<fieldset class="field checks" ${disabled?'disabled':''}><legend>${esc(f.label)}</legend>${f.options.map((o,i)=>`<label><input type="checkbox" data-field="${f.id}" value="${esc(o)}" ${value.split('\n').includes(o)?'checked':''}>${esc(o)}</label>`).join('')}</fieldset>`;
 const input=f.type==='select'?`<select ${attrs}><option value="">Selecione</option>${f.options.map(o=>`<option ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select>`:f.type==='textarea'?`<textarea ${attrs} maxlength="20000" rows="8">${esc(value)}</textarea><small class="counter" id="count-${f.id}">${value.length.toLocaleString('pt-BR')} / 20.000 caracteres</small>`:`<input ${attrs} type="${f.type==='date'?'date':'text'}" value="${esc(value)}" maxlength="${f.type==='signature'?20000:2000}">`;
 return `<div class="field">${label}${input}</div>`;}
function sectionBody(){const c=state.current,sec=currentSec(),def=templates[c.document.kind].sections.find(s=>s.id===sec.key),locked=sec.status!=='draft'||c.document.status==='final';
 return `<div class="section-heading"><div><span class="card-kicker">PREENCHIMENTO POR ÁREA</span><h2>${esc(def.title)}</h2></div><span class="badge ${sec.status}">${statusLabel[sec.status]}</span></div>${def.hint?`<details class="guidance" open><summary>Orientações para preencher</summary><p>${esc(def.hint)}</p></details>`:''}${sec.feedback?`<div class="feedback"><strong>Comentário da gestão</strong><p>${esc(sec.feedback)}</p></div>`:''}${locked?'<p class="callout">Área protegida para revisão. O administrador pode reabrir o preenchimento.</p>':''}<form id="section-form">${def.fields.map(f=>fieldInput(f,sec.values[f.id]||'',locked)).join('')}</form><div class="editor-actions"><span id="save-status" class="save-status" role="status">${saveStatus(sec.key)}</span><button id="resolve-conflict" data-action="resolve-conflict" ${state.errors.get(sec.key)?.includes('CONFLICT')?'':'hidden'}>Comparar versões antes de salvar</button><div class="actions">${!locked?'<button data-action="save">Salvar agora</button>':''}${state.role==='admin'&&c.document.status!=='final'?`${sec.status!=='approved'?'<button class="primary" data-action="approve">Aprovar área ✓</button>':''}<button data-action="review">${locked?'Reabrir / pedir ajuste':'Comentar'}</button>`:''}${state.role==='admin'?'<button class="text-button" data-action="history">Histórico</button>':''}</div></div>`;
}
function saveStatus(key){if(state.errors.has(key))return 'Falha ao salvar. Texto preservado nesta aba.';if(state.pending.has(key))return 'Salvando…';if(state.dirty.has(key))return 'Alterações ainda não salvas';const sec=state.current.sections.find(s=>s.key===key);return sec.version?'Salvo no banco · '+stamp(sec.updated_at):'Sem alterações';}
function updateSaveStatus(){const el=document.querySelector('#save-status');if(el)el.textContent=saveStatus(state.section);const resolve=document.querySelector('#resolve-conflict');if(resolve)resolve.hidden=!state.errors.get(state.section)?.includes('CONFLICT');}
function invitesBody(){const c=state.current;return `<section class="card"><div class="panel-title"><div><h2>Contribuições da equipe</h2><p class="muted">Escolha as áreas, gere o link e envie à pessoa responsável.</p></div>${c.document.status!=='final'?'<button class="primary" data-action="new-invite">＋ Gerar convite</button>':''}</div><p class="hint">O link permite acessar os dados das áreas selecionadas. Compartilhe individualmente. O nome do convite identifica o acesso, mas não verifica a identidade de quem o utiliza.</p>${c.invitations?.length?`<div class="invite-list">${c.invitations.map(i=>{const expired=new Date(i.expires_at)<new Date();return `<div class="invite-row"><div><strong>${esc(i.label)}</strong><p>${i.scopes.map(k=>esc(templates[c.document.kind].sections.find(s=>s.id===k)?.title||k)).join(' · ')}</p><small>${i.revoked_at?'Revogado':expired?'Expirado':'Válido até '+stamp(i.expires_at)}</small></div>${!i.revoked_at&&!expired?`<button data-action="revoke" data-id="${i.id}">Revogar</button>`:''}</div>`;}).join('')}</div>`:'<div class="empty"><h3>Nenhum convite gerado</h3><p>Você pode preencher sozinho ou distribuir as áreas entre os profissionais.</p></div>'}</section>`;}
function editionsBody(){return `<section class="card"><h2>Edições preservadas</h2><p class="muted">Cada finalização guarda uma cópia das respostas. Reabrir o trabalho não altera os PDFs das edições anteriores.</p>${state.current.editions?.length?state.current.editions.map(e=>`<div class="invite-row"><div><strong>Edição ${e.edition}</strong><p>Finalizada em ${stamp(e.created_at)}</p></div><button data-action="edition-pdf" data-id="${e.id}">↓ Baixar PDF</button></div>`).join(''):'<div class="empty"><h3>Nenhuma edição finalizada</h3><p>Aprove todas as áreas e finalize o documento.</p></div>'}</section>`;}
function dialog(title,body){document.querySelector('dialog')?.remove();const el=document.createElement('dialog');el.innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2><button data-action="close-dialog" aria-label="Fechar">×</button></div>${body}`;document.body.append(el);el.showModal();return el;}
const formActions=(label)=>`<div class="dialog-actions"><button type="button" data-action="close-dialog">Cancelar</button><button class="primary">${label}</button></div>`;
function studentForm(edit=false){const s=edit?state.student:{};dialog(edit?'Editar estudante':'Cadastrar estudante',`<form id="student-form" data-edit="${edit}"><label>Nome completo<input name="name" value="${esc(s.name||'')}" maxlength="200" required autofocus></label><label>Ano/série e turma<input name="grade" value="${esc(s.grade||'')}" maxlength="100" required placeholder="Ex.: 6º ano A"></label><label>Data de nascimento (opcional)<input name="birth_date" type="date" value="${s.birth_date||''}"></label>${edit?'<p class="hint">Esta alteração atualiza o cadastro. Revise a identificação nos documentos já criados; suas respostas não são sobrescritas.</p>':''}${formActions(edit?'Salvar cadastro':'Cadastrar estudante')}</form>`);}
function newDocument(){dialog('Criar documento',`<form id="document-form"><label>Modelo<select name="kind">${Object.entries(templates).map(([k,t])=>`<option value="${k}">${t.name}</option>`).join('')}</select></label><div class="form-grid"><label>Ano letivo<input type="number" name="year" min="2020" max="2100" value="${new Date().getFullYear()}" required></label><label id="term-label" hidden>Bimestre<select name="term">${[1,2,3,4].map(n=>`<option value="${n}">${n}º bimestre</option>`).join('')}</select></label></div><label id="subject-label" hidden>Componente curricular<input name="subject" maxlength="150" placeholder="Ex.: Língua Portuguesa"></label><label>Prazo de preenchimento (opcional)<input name="due_date" type="date"></label><p class="hint">Defina o prazo conforme o calendário e as orientações da gestão. Dias letivos não são convertidos automaticamente em dias corridos.</p>${formActions('Criar documento')}</form>`);}
function newInvite(){const c=state.current;dialog('Gerar convite por área',`<form id="invite-form"><label>Responsável pelo preenchimento<input name="label" maxlength="150" required placeholder="Ex.: Professora de Língua Portuguesa"></label><label>Validade do convite<select name="days"><option value="7">7 dias</option><option value="15" selected>15 dias</option><option value="30">30 dias</option><option value="60">60 dias</option><option value="90">90 dias</option></select></label><fieldset class="checks"><legend>Áreas que a pessoa poderá ler e preencher</legend>${templates[c.document.kind].sections.map(s=>{const row=c.sections.find(v=>v.key===s.id);return `<label><input type="checkbox" name="scope" value="${s.id}" ${row.status!=='draft'?'disabled':''}>${esc(s.title)}${row.status!=='draft'?' (protegida)':''}</label>`;}).join('')}</fieldset><p class="hint">Identificação, família e assinaturas podem conter informações pessoais. Selecione somente o necessário para essa contribuição.</p>${formActions('Gerar link de acesso')}</form>`);}
async function saveSection(key){
 clearTimeout(state.timers.get(key));
 if(state.pending.has(key)){await state.pending.get(key);if(!state.dirty.has(key))return;}
 if(!state.dirty.has(key))return;
 const sec=state.current.sections.find(s=>s.key===key),values=structuredClone(sec.values),id=state.current.document.id;
 state.dirty.delete(key);state.errors.delete(key);
 const work=api.save(id,key,values,sec.version,token).then(saved=>{
   const unsaved=sec.values;Object.assign(sec,saved);if(state.dirty.has(key))sec.values=unsaved;
 }).catch(e=>{state.dirty.add(key);state.errors.set(key,e.message);throw e;}).finally(()=>{state.pending.delete(key);updateSaveStatus();});
 state.pending.set(key,work);updateSaveStatus();await work;
}
async function flush(){for(const timeout of state.timers.values())clearTimeout(timeout);while(state.pending.size||state.dirty.size){await Promise.all([...state.pending.values()]);for(const key of [...state.dirty])await saveSection(key);}}
async function openDocument(id){await flush();state.current=await api.admin('get',{id});state.section=templates[state.current.document.kind].sections[0].id;state.tab='fields';editor();}
async function refreshDocument(){const key=state.section;state.current=state.role==='admin'?await api.admin('get',{id:state.current.document.id}):await api.openInvite(token);state.section=key;editor();}
async function home(){await flush();state.current=null;if(state.role==='admin'){await loadDashboard();dashboard();}else if(state.role==='contributor'){await openContributor();}else login();}
async function openContributor(){if(!api)throw Error('O acesso ainda não foi ativado. Procure o administrador.');state.current=await api.openInvite(token);state.role='contributor';state.tab='fields';state.section=state.current.sections[0].key;editor();}
async function pdfExport(editionId){await flush();let snap;if(editionId)snap=await api.admin('edition',{id:state.current.document.id,edition_id:editionId});else{await refreshDocument();snap=state.current;if(snap.document.status==='final')snap=await api.admin('edition',{id:snap.document.id,edition_id:snap.editions[0].id});}notify('Preparando o PDF…');await downloadPdf(snap);notify('PDF preparado para download.');}
async function history(){await flush();const rows=await api.admin('history',{id:state.current.document.id,key:state.section});dialog('Histórico desta área',`<p class="muted">Restaurar cria uma nova revisão e preserva o histórico.</p><div class="history">${rows.map(r=>`<details><summary>Revisão ${r.version} · ${stamp(r.created_at)}<small>${esc(r.actor)} · ${statusLabel[r.status]}</small></summary><dl>${Object.entries(r.values).map(([k,v])=>`<dt>${esc(templates[state.current.document.kind].sections.find(s=>s.id===state.section).fields.find(f=>f.id===k)?.label||k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>${currentSec().status==='draft'&&state.current.document.status!=='final'?`<button data-action="restore" data-id="${r.id}">Restaurar esta revisão</button>`:''}</details>`).join('')}</div>`);}
async function resolveConflict(){
 const fresh=state.role==='admin'?await api.admin('get',{id:state.current.document.id}):await api.openInvite(token);
 state.conflict=fresh.sections.find(s=>s.key===state.section);
 const describe=sec=>templates[state.current.document.kind].sections.find(s=>s.id===sec.key).fields.map(f=>f.label+'\n'+(sec.values[f.id]||'')).join('\n\n');
 dialog('Comparar versões da área',`<p class="hint">Outra sessão alterou esta área. Confira os dois textos antes de escolher.</p><label>Seu texto nesta aba<textarea rows="8" readonly>${esc(describe(currentSec()))}</textarea></label><label>Versão salva no banco<textarea rows="8" readonly>${esc(describe(state.conflict))}</textarea></label><div class="actions"><button data-action="use-saved">Usar a versão do banco</button><button class="primary" data-action="keep-mine" ${state.conflict.status!=='draft'?'disabled':''}>Salvar meu texto como nova revisão</button></div>`);
}
const actions={
 'forgot-password':()=>dialog('Recuperar senha',`<form id="recovery-form"><label>E-mail da conta<input name="email" type="email" autocomplete="username" required></label><p class="hint">Você receberá um link para criar uma nova senha.</p>${formActions('Enviar link de recuperação')}</form>`),
 'resolve-conflict':resolveConflict,
 'use-saved':()=>{clearTimeout(state.timers.get(state.section));Object.assign(currentSec(),state.conflict);state.dirty.delete(state.section);state.errors.delete(state.section);document.querySelector('dialog').close();editor();},
 'keep-mine':async()=>{const sec=currentSec();const saved=await api.save(state.current.document.id,sec.key,sec.values,state.conflict.version,token);Object.assign(sec,saved);state.dirty.delete(sec.key);state.errors.delete(sec.key);clearTimeout(state.timers.get(sec.key));document.querySelector('dialog').close();editor();},
 home,guide:async()=>{await flush();guide();},catalogue:async id=>{await flush();catalogue(id);},'new-student':()=>studentForm(),'edit-student':()=>studentForm(true),
 student:async id=>{await flush();state.student=state.students.find(s=>s.id===id);state.current=null;studentPage();},
 'student-back':async()=>{await flush();state.student=state.students.find(s=>s.id===state.current.document.student_id)||state.student;state.current=null;await loadDashboard();studentPage();},
 'new-document':newDocument,document:openDocument,deadline:async()=>{await flush();dialog('Ajustar prazo',`<form id="deadline-form"><label>Prazo de preenchimento<input name="due_date" type="date" value="${state.current.document.due_date||''}"></label>${formActions('Salvar prazo')}</form>`);},
 section:async id=>{await flush();if(!state.current.sections.some(s=>s.key===id))throw Error('Área não autorizada.');state.section=id;editor();},
 tab:async id=>{await flush();state.tab=id;editor();},save:async()=>{await flush();notify('Respostas salvas no banco.');},
 approve:async()=>{await flush();await api.admin('review',{id:state.current.document.id,key:state.section,version:currentSec().version,status:'approved'});await refreshDocument();},
 review:async()=>{await flush();dialog('Comentário e ajuste da área',`<form id="review-form"><label>Orientação para quem preenche<textarea name="feedback" maxlength="5000" rows="5">${esc(currentSec().feedback)}</textarea></label><p class="hint">A área voltará ao preenchimento. Convites ainda válidos poderão editar novamente.</p>${formActions('Salvar e abrir preenchimento')}</form>`);},
 history,restore:async id=>{await api.admin('restore',{id:state.current.document.id,key:state.section,version:currentSec().version,revision_id:id});document.querySelector('dialog').close();await refreshDocument();notify('Revisão restaurada em uma nova versão.');},
 'new-invite':newInvite,revoke:async id=>{await api.admin('revoke_invite',{id:state.current.document.id,invitation_id:id});await refreshDocument();notify('Convite revogado.');},
 'copy-invite':async()=>{const field=document.querySelector('#invite-link');try{await navigator.clipboard.writeText(field.value);notify('Link copiado. Envie individualmente à pessoa responsável.');}catch{field.select();notify('Selecione e copie o link exibido.');}},
 'close-dialog':()=>document.querySelector('dialog')?.close(),
 'submit-invite':async()=>{await flush();state.current=await api.submit(token,Object.fromEntries(state.current.sections.map(s=>[s.key,s.version])));editor();notify('Áreas enviadas para revisão.');},
 'invite-refresh':async()=>{await flush();await openContributor();},
 finalize:async()=>{await flush();await api.admin('finalize',{id:state.current.document.id});await refreshDocument();notify('Edição finalizada. Os convites foram encerrados.');},
 'reopen-document':async()=>{await api.admin('reopen_document',{id:state.current.document.id});await refreshDocument();notify('Nova edição aberta. A edição anterior está preservada.');},
 pdf:()=>pdfExport(),'edition-pdf':pdfExport,
 logout:async()=>{await flush();await api.logout();state.current=null;state.students=[];state.documents=[];state.student=null;state.role=null;login();}
};
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;e.preventDefault();if(b.disabled)return;const action=actions[b.dataset.action];if(!action)return;b.disabled=true;const editable=[...document.querySelectorAll("[data-field]:not(:disabled)")];editable.forEach(x=>x.disabled=true);try{await action(b.dataset.id);}catch(err){failure(err);}finally{b.disabled=false;editable.forEach(x=>{if(x.isConnected)x.disabled=false;});}});
document.addEventListener('input',e=>{
 if(e.target.id==='search'){state.filter=e.target.value;document.querySelector('#student-results').innerHTML=studentRows(state.students.filter(s=>(s.name+' '+s.grade).toLocaleLowerCase('pt-BR').includes(state.filter.toLocaleLowerCase('pt-BR'))));return;}
 const field=e.target.dataset.field;if(!field||!state.current)return;const sec=currentSec();
 if(sec.status!=='draft'||state.current.document.status==='final')return;
 sec.values[field]=e.target.type==='checkbox'?[...document.querySelectorAll(`input[data-field="${field}"]:checked`)].map(x=>x.value).join('\n'):e.target.value;
 state.dirty.add(sec.key);const count=document.querySelector('#count-'+field);if(count)count.textContent=`${sec.values[field].length.toLocaleString('pt-BR')} / 20.000 caracteres`;
 clearTimeout(state.timers.get(sec.key));state.timers.set(sec.key,setTimeout(()=>saveSection(sec.key).catch(failure),1200));updateSaveStatus();
});
document.addEventListener('change',e=>{if(e.target.name==='kind'){const type=templates[e.target.value].period;document.querySelector('#term-label').hidden=!['subject','term'].includes(type);document.querySelector('#subject-label').hidden=type!=='subject';document.querySelector('[name=subject]').required=type==='subject';}});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,button=form.querySelector('button.primary');if(button?.disabled)return;if(button)button.disabled=true;const data=new FormData(form);
 try{
 if(form.id==='login-form'){const rows=await api.login(data.get('email'),data.get('password'));state.students=rows.students;state.documents=rows.documents;state.role='admin';dashboard();}
 else if(form.id==='recovery-form'){await api.requestPasswordReset(data.get('email'));document.querySelector('dialog').close();notify('Enviamos o link de recuperação. Abra o e-mail nesta mesma janela.');}
 else if(form.id==='new-password-form'){const password=data.get('password');if(password!==data.get('confirm'))throw Error('As senhas não coincidem.');await api.updatePassword(password);history.replaceState(null,'',location.pathname);const rows=await api.admin('list');state.students=rows.students;state.documents=rows.documents;state.role='admin';dashboard();notify('Nova senha salva. Acesso liberado.');}
 else if(form.id==='student-form'){const editing=form.dataset.edit==='true';const s=await api.admin(editing?'update_student':'create_student',{...Object.fromEntries(data),...(editing?{id:state.student.id}:{})});document.querySelector('dialog').close();await loadDashboard();state.student=s;studentPage();}
 else if(form.id==='document-form'){const payload=Object.fromEntries(data),type=templates[payload.kind].period;payload.term=['subject','term'].includes(type)?Number(payload.term):0;payload.subject=type==='subject'?payload.subject.trim():'';payload.student_id=state.student.id;payload.initial=initialValues(payload.kind,state.student,payload.term,payload.subject);const c=await api.admin('create_document',payload);document.querySelector('dialog').close();await loadDashboard();await openDocument(c.document.id);}
 else if(form.id==='invite-form'){const scopes=data.getAll('scope');if(!scopes.length)throw Error('Selecione pelo menos uma área.');const secret=randomToken();const expires=new Date(Date.now()+Number(data.get('days'))*86400000).toISOString();await api.admin('create_invite',{id:state.current.document.id,label:data.get('label'),scopes,expires_at:expires,token:secret});await refreshDocument();dialog('Convite criado',`<p>Copie este link e envie diretamente a <strong>${esc(data.get('label'))}</strong>.</p><label>Link de acesso<textarea id="invite-link" rows="4" readonly>${esc(inviteUrl(secret))}</textarea></label><p class="hint">O link é mostrado apenas agora. Se perdê-lo, revogue o convite e gere outro.</p><button class="primary" data-action="copy-invite">Copiar link</button>`);}
 else if(form.id==='deadline-form'){await api.admin('set_due_date',{id:state.current.document.id,due_date:data.get('due_date')});document.querySelector('dialog').close();await refreshDocument();}
 else if(form.id==='review-form'){await api.admin('review',{id:state.current.document.id,key:state.section,version:currentSec().version,status:'draft',feedback:data.get('feedback')});document.querySelector('dialog').close();await refreshDocument();}
 }catch(err){failure(err);}finally{if(button)button.disabled=false;}
});
window.addEventListener('beforeunload',e=>{if(state.dirty.size||state.pending.size){e.preventDefault();e.returnValue='';}});
window.addEventListener('online',()=>{if(state.dirty.size)notify('Conexão restabelecida. Use “Salvar agora” para tentar novamente.');});
window.addEventListener('hashchange',async()=>{const next=new URLSearchParams(location.hash.slice(1)).get('convite');if(next===token)return;try{await flush();if(state.role==='admin')await api.logout();token=next;state.current=null;state.role=null;if(token)await openContributor();else login();}catch(e){failure(e);}});
// Ferramenta de navegação: não retorna textos dos estudantes nem executa escrita.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'abrir_guia_formulario',title:'Abrir guia de formulário',description:'Mostra as perguntas e as áreas de um dos cinco formulários. Não cria documentos nem preenche respostas.',inputSchema:{type:'object',properties:{modelo:{type:'string',enum:Object.keys(templates)}},required:['modelo'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:async input=>{if(!input||Object.keys(input).length!==1||!Object.hasOwn(templates,input.modelo))throw Error('Modelo inválido.');await flush();catalogue(input.modelo);return {modelo:input.modelo,areas:templates[input.modelo].sections.length,tela:'guia'};}})).catch(()=>{});}catch{}}
if(api)api.onAuth(event=>{if(event==='PASSWORD_RECOVERY')setTimeout(passwordRecovery,0);});
if(token){openContributor().catch(e=>{shell(`<section class="card access-error"><h1>Não foi possível abrir o convite</h1><p>${esc(e.message)}</p><p>Peça ao administrador um novo link, se necessário.</p><button data-action="invite-refresh">Tentar novamente</button></section>`);});}else login();
