import {createClient} from '@supabase/supabase-js';
import {randomToken,configured} from './api.js';
import {downloadRoutinePdf} from './routines-pdf.js';
const root=document.querySelector('#app'),notice=document.querySelector('#notice');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const days=['Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira'];
const labels={draft:'Rascunho',submitted:'Enviada',changes:'Ajustes solicitados',approved:'Aprovada'};
const defaultSlots=['07:00 às 07:50','07:50 às 08:40','08:55 às 09:45','09:45 às 10:35','10:35 às 11:25','11:25 às 12:15'];
export function monday(value){const d=new Date(value+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return d.toISOString().slice(0,10);}
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const date=v=>v.split('-').reverse().join('/');
const offset=(v,n)=>{const d=new Date(v+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const yearWeek=year=>{const current=monday(today());return Number(offset(current,3).slice(0,4))===year?current:monday(`${year}-01-04`);};
let token=new URLSearchParams(location.hash.slice(1)).get('professor'),admin=false,client;
let catalogue={teachers:[],schedules:[],weeks:[]},current=null,dirty=false,busy=false,selectedWeek=monday(today());
function notify(text,error=false){notice.textContent=text;notice.className=error?'error':'success';}
function fail(e){notify(e.message?.includes('Failed to fetch')?'Sem conexão. Seu texto continua nesta tela. Tente salvar novamente.':e.message||'Não foi possível concluir.',true);}
async function rpc(action,data={}){const {data:result,error}=await client.rpc('ee_routines',{p_action:action,p_data:data,p_token:token||null});if(error)throw Error(error.message);return result;}
function frame(body){root.innerHTML=`<header><div><a href="../">Luigi Pirandello</a><span>Gestão pedagógica / Rotinas</span></div><nav><a href="../">Educação Especial</a>${admin?'<button data-action="home">Professores</button><button data-action="logout">Sair</button>':''}</nav></header><main id="conteudo">${body}</main><footer>E.E. Luigi Pirandello · Planejamento semanal</footer>`;}
function login(){frame(`<section class="intro"><p class="eyebrow">PLANEJAMENTO E ACOMPANHAMENTO</p><h1>Rotinas dos professores</h1><p>Uma semana de cada vez. Planeje as aulas e acompanhe as devolutivas da coordenação.</p></section><section class="card narrow"><h2>Acesso da coordenação</h2><form id="login"><label>E-mail<input name="email" type="email" autocomplete="username" required></label><label>Senha<input name="password" type="password" autocomplete="current-password" required></label><button class="primary">Entrar</button></form><p>Professores acessam pelo link individual enviado pela coordenação.</p><a href="../">Recuperar senha na página principal</a></section>`);}
function safeToLeave(){return !dirty||confirm('Há alterações não salvas. Deseja descartá-las?');}
function setDirty(value){dirty=value;const el=document.querySelector('#save-state');if(el)el.textContent=value?'Alterações não salvas':'Tudo salvo';}
async function home(){catalogue=await rpc('list');current=null;setDirty(false);renderHome();}
function renderHome(){const chosen=selectedWeek,year=Number(offset(chosen,3).slice(0,4));frame(`<section class="intro"><p class="eyebrow">ÁREA DA COORDENAÇÃO</p><h1>Rotinas semanais</h1><p>Configure os horários, cadastre os professores e acompanhe cada semana.</p></section><div class="toolbar"><label>Semana de<input type="date" id="dashboard-week" value="${chosen}"></label><span>${date(chosen)} a ${date(offset(chosen,4))}</span></div><section class="teacher-grid">${catalogue.teachers.filter(t=>t.year===year).map(t=>{const w=catalogue.weeks.find(w=>w.teacher_id===t.id&&w.week===chosen);return `<article class="card"><p class="eyebrow">${esc(t.class_name)} · ${t.year}</p><h2>${esc(t.name)}</h2><p class="badge">${w?labels[w.status]:'Ainda não preenchida'}</p><button class="primary" data-action="open" data-id="${t.id}">Abrir semana</button><div class="link-actions"><button data-action="rotate" data-id="${t.id}">${t.active?'Gerar novo link':'Ativar link'}</button>${t.active?`<button data-action="revoke" data-id="${t.id}">Revogar link</button>`:''}</div></article>`;}).join('')||'<p>Nenhum professor cadastrado para este ano.</p>'}</section><div class="setup-grid"><section class="card"><h2>Cadastrar professor</h2><form id="teacher"><label>Nome<input name="name" maxlength="150" required></label><label>Turma<input name="class_name" maxlength="100" placeholder="Ex.: 1º A" required></label><label>Ano letivo<input name="year" type="number" min="2020" max="2100" value="${year}" required></label><button class="primary">Cadastrar e gerar link</button></form><p>O link permite acessar apenas a rotina deste professor e ano. Guarde-o para compartilhar.</p></section><section class="card"><h2>Horários da escola</h2><p>Um horário por linha, na ordem das aulas. Até 12 aulas. Valem para todos os professores; semanas já salvas mantêm os horários anteriores.</p><form id="schedule"><label>Aplicar às novas rotinas a partir de<input name="effective" type="date" value="${monday(`${year}-01-04`)}" required></label><label>Horários<textarea name="slots" rows="8" required>${esc((catalogue.schedules.find(s=>s.effective<=chosen)?.slots||defaultSlots).join('\n'))}</textarea></label><button class="primary">Salvar horários para todos</button></form><details><summary>Configurações salvas (${catalogue.schedules.length})</summary>${catalogue.schedules.map(s=>`<p>A partir de ${date(s.effective)}: ${esc(s.slots.join(' · '))}</p>`).join('')}</details></section></div>`);}
function showLink(secret){const url=new URL(location.href);url.search='';url.hash=`professor=${secret}`;const dialog=document.createElement('dialog');dialog.innerHTML=`<h2>Link individual do professor</h2><p>Copie e envie ao professor. Quem tiver este link poderá preencher a rotina.</p><label>Link<input id="teacher-link" readonly value="${esc(url.href)}"></label><button id="copy-link" class="primary">Copiar link</button><form method="dialog"><button>Fechar</button></form>`;document.body.append(dialog);dialog.showModal();dialog.querySelector('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(url.href);dialog.querySelector('#copy-link').textContent='Copiado';}catch{dialog.querySelector('input').select();notify('Selecione o link e copie manualmente.');}};dialog.addEventListener('close',()=>dialog.remove());}
async function openWeek(id,week){const data=await rpc('get',{id,week});current=data;selectedWeek=data.week;setDirty(false);renderWeek();}
function field(key,label,long=false){return `<label>${label}${long?`<textarea rows="5" name="${key}" maxlength="12000">${esc(current.content[key]||'')}</textarea>`:`<input name="${key}" maxlength="12000" value="${esc(current.content[key]||'')}">`}</label>`;}
function renderWeek(){const t=current.teacher;frame(`<section class="intro"><p class="eyebrow">${esc(t.class_name)} · ${t.year}</p><h1>${esc(t.name)}</h1><p>Rotina de ${date(current.week)} a ${date(offset(current.week,4))}</p></section><div class="toolbar"><button data-action="previous">Semana anterior</button><label>Escolher semana<input id="week" type="date" value="${current.week}"></label><button data-action="next">Próxima semana</button><span class="badge">${labels[current.status]}</span>${admin?'<button data-action="pdf">Baixar PDF</button>':''}</div>${!current.slots?'<section class="card">A coordenação precisa configurar os horários para esta semana.</section>':`<form id="routine"><div class="savebar"><span id="save-state" role="status">${current.version?'Tudo salvo':'Semana ainda não salva'}</span><button type="button" data-action="copy-subjects">Copiar disciplinas da semana anterior</button><button name="save" class="primary">Salvar rascunho</button><button name="submit">Salvar e enviar para revisão</button></div><p>Preencha as disciplinas e o conteúdo, objetivos, habilidades e metodologia de cada aula. Salve antes de mudar de semana.</p><div class="table-scroll"><table><thead><tr><th>Horário</th>${days.map((d,i)=>`<th>${d}<small>${date(offset(current.week,i))}</small></th>`).join('')}</tr></thead><tbody><tr><th>Leitura inicial</th>${days.map((d,i)=>`<td>${field(`d${i}_reading`,'Leitura')}${field(`d${i}_author`,'Autor')}${field(`d${i}_genre`,'Gênero')}</td>`).join('')}</tr>${current.slots.map((slot,s)=>`<tr><th>${s+1}ª aula<small>${esc(slot)}</small></th>${days.map((d,i)=>`<td>${field(`d${i}_s${s}_subject`,'Disciplina')}${field(`d${i}_s${s}_content`,'Conteúdo / Objetivos / Habilidades',true)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><section class="card extra-fields">${field('notes','Observações das atividades',true)}${field('difficulties','Estudantes com dificuldades de aprendizagem',true)}${field('absences','Estudantes faltosos da semana',true)}</section><button class="primary">Salvar rascunho</button></form>`}<section class="card reviews"><h2>Devolutivas da coordenação</h2>${current.comments.map(c=>`<article><strong>${labels[c.status]}</strong><small>${new Date(c.created_at).toLocaleString('pt-BR')} · versão ${c.version}</small><p class="prewrap">${esc(c.body)}</p></article>`).join('')||'<p>Ainda não há comentários para esta semana.</p>'}${admin&&current.version?`<form id="review"><label>Comentário<textarea name="body" required maxlength="5000" rows="4" placeholder="Indique o dia e a aula, quando necessário."></textarea></label><label>Avaliação<select name="status"><option value="changes">Solicitar ajustes</option><option value="approved">Aprovar rotina</option></select></label><button class="primary">Registrar devolutiva</button></form>`:''}</section>`);}
root.addEventListener('input',e=>{if(e.target.closest('#routine'))setDirty(true);});
root.addEventListener('change',async e=>{if(!['week','dashboard-week'].includes(e.target.id))return;if(!safeToLeave()){e.target.value=selectedWeek;return;}try{const w=monday(e.target.value);if(e.target.id==='week')await openWeek(current.teacher.id,w);else{selectedWeek=w;renderHome();}}catch(err){e.target.value=selectedWeek;fail(err);}});
async function locked(fn){if(busy)return;busy=true;const buttons=[...root.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){fail(e);}finally{busy=false;buttons.forEach(b=>b.disabled=false);}}
root.addEventListener('submit',e=>{e.preventDefault();const form=e.target,values=Object.fromEntries(new FormData(form)),submitted=e.submitter?.name==='submit';locked(async()=>{
 if(form.id==='login'){const {error}=await client.auth.signInWithPassword(values);if(error)throw Error('Não foi possível entrar. Confira o e-mail e a senha.');await rpc('list');admin=true;await home();}
 if(form.id==='teacher'){const secret=randomToken();await rpc('create_teacher',{...values,year:Number(values.year),token:secret});await home();showLink(secret);}
 if(form.id==='schedule'){await rpc('schedule',{effective:monday(values.effective),slots:values.slots.split('\n').map(s=>s.trim()).filter(Boolean)});await home();notify('Horários salvos. Serão usados nas novas semanas de todos os professores.');}
 if(form.id==='routine'){
  // Keep the form editable during the request and retain any edits made while saving.
  const sent=JSON.stringify(values);const result=await rpc('save',{id:current.teacher.id,week:current.week,slots:current.slots,version:current.version,content:values,status:submitted?'submitted':'draft'});
  current.version=result.version;current.status=result.status;current.content=values;
  setDirty(JSON.stringify(Object.fromEntries(new FormData(form)))!==sent);
  const badge=root.querySelector('.toolbar .badge');if(badge)badge.textContent=labels[result.status];
  notify(dirty?'Versão salva. Há novas alterações nesta tela para salvar.':'Rotina salva com sucesso.');
 }
 if(form.id==='review'){if(dirty)throw Error('Salve as alterações na rotina antes de avaliar.');await rpc('review',{id:current.teacher.id,week:current.week,version:current.version,...values});await openWeek(current.teacher.id,current.week);notify('Devolutiva registrada.');}
});});
root.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;locked(async()=>{
 if(['home','logout','open','previous','next'].includes(action)&&!safeToLeave())return;
 if(action==='home')await home();
 if(action==='logout'){await client.auth.signOut({scope:'local'});admin=false;current=null;setDirty(false);login();}
 if(action==='open')await openWeek(b.dataset.id,selectedWeek);
 if(action==='previous'||action==='next')await openWeek(current.teacher.id,offset(current.week,action==='next'?7:-7));
 if(action==='rotate'){if(!confirm('Gerar um novo link? O link anterior deixará de funcionar.'))return;const secret=randomToken();await rpc('rotate',{id:b.dataset.id,token:secret});await home();showLink(secret);}
 if(action==='revoke'){if(!confirm('Revogar o acesso deste professor? As rotinas serão preservadas.'))return;await rpc('revoke',{id:b.dataset.id});await home();notify('Link revogado.');}
 if(action==='copy-subjects'){
  if(!confirm('Copiar as disciplinas da semana anterior somente para os campos vazios?'))return;
  const prior=await rpc('get',{id:current.teacher.id,week:offset(current.week,-7)});let count=0;
  for(const input of root.querySelectorAll('#routine input[name$="_subject"]'))if(!input.value&&prior.content[input.name]){input.value=prior.content[input.name];count++;}
  if(count)setDirty(true);notify(count?`${count} disciplinas copiadas. Salve a rotina.`:'Nenhuma disciplina disponível para copiar.');
 }
 if(action==='pdf'){if(dirty)throw Error('Salve as alterações antes de gerar o PDF.');const saved=await rpc('get',{id:current.teacher.id,week:current.week});if(!saved.version)throw Error('Esta semana ainda não foi salva.');await downloadRoutinePdf(saved);}
});});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
root.addEventListener('click',e=>{if(e.target.closest('a')&&!safeToLeave())e.preventDefault();});
async function start(){if(!configured(window.ESCOLA_CONFIG))throw Error('Configuração da plataforma indisponível.');client=createClient(window.ESCOLA_CONFIG.supabaseUrl,window.ESCOLA_CONFIG.supabasePublishableKey,{auth:{persistSession:false,autoRefreshToken:true,detectSessionInUrl:false}});if(token){const t=await rpc('identity');await openWeek(t.id,yearWeek(t.year));}else login();}
start().catch(e=>{frame('<section class="card"><h1>Não foi possível abrir a rotina</h1><p>Peça à coordenação um link ativo ou tente novamente.</p><button data-action="reload">Tentar novamente</button></section>');root.querySelector('button').onclick=()=>location.reload();fail(e);});
